### PR TITLE
Kotlin version upgrade

### PR DESCRIPTION
**Pull request by pradyotprksh**
- Upgrade the version for Kotlin

Please check this PR and merge it for upgrading the Kotlin version.
Thanks.

### CODE REVIEW

**Comment by caiopo** [comment]
Hi! Thank you for the contribution, I'll try to take a look at it later today or tomorrow. :)

**Comment by pradyotprksh** [comment]
sorry to bother, but did you had a look into this?

**Comment by caiopo** [comment]
Hi @pradyotprksh!

Sorry for the delay.

Just published 0.4.0 with the update PR (and another commit upgrading Gradle too, because the old Gradle version was too old for Kotlin 1.8).

https://pub.dev/packages/installer_info/versions/0.4.0

Let me know if you encounter any issue with the update.

Thank you again for your contribution! :)

**Comment by pradyotprksh** [comment]
`and another commit upgrading Gradle too, because the old Gradle version was too old for Kotlin 1.8` oh didn't saw this issue on my end but cool.

thanks will use the latest version 🙏

**Pull request merged**
